---
title: "classification k-mer"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#install.packages("stringr", dependencies=TRUE)
library(stringr)
```

```{r}
Data = read.csv('~/Documents/Data/mouse/All/MM_all_G4InTranscript.txt', header = F, sep = "\t")
colnames(Data) = c("InfoG4ByTranscript","cGcC","G4Hunter","sequenceG4","G4NN","localisation","transcriptBiotype")
```

## Analyse

```{r}
table_biotype = table(Data$transcriptBiotype)
```

## Petite famille : IG_C_gene

```{r}
which(Data$transcriptBiotype == "IG_C_gene")
Data_IG_C_gene = which(Data$transcriptBiotype== "IG_C_gene")
Data_IG_C_gene = Data[Data_IG_C_gene,]
pie(table(Data_IG_C_gene[,6]))
table(str_length(Data_IG_C_gene[,4]))
Data_IG_C_gene[,4]
```

Pour cette famille il y a 11 rG4s. Il y en a 3 en 3', 6 en Intron et 2 Sur des jonctions CDS-Intron. 63% de ces rG4s font 60 nucléotides de longs.


## Petite famille : IG_V_gene

```{r}
which(Data$transcriptBiotype == "IG_V_gene")
Data_IG_V_gene = which(Data$transcriptBiotype == "IG_V_gene")
Data_IG_V_gene = Data[Data_IG_V_gene,]
pie(table(Data_IG_V_gene[,6]))
table(str_length(Data_IG_V_gene[,4]))
Data_IG_V_gene[,4]
```

## Petite famille : TR_C_gene

```{r}
which(Data$transcriptBiotype == "TR_C_gene")
Data_TR_C_gene = which(Data$transcriptBiotype == "TR_C_gene")
Data_TR_C_gene = Data[Data_TR_C_gene,]
pie(table(Data_TR_C_gene[,6]))
table(str_length(Data_TR_C_gene[,4]))
Data_TR_C_gene[,4]
```

## Petite famille : TR_V_gene

```{r}
which(Data$transcriptBiotype == "TR_V_gene")
Data_TR_V_gene = which(Data$transcriptBiotype == "TR_V_gene")
Data_TR_V_gene = Data[Data_TR_V_gene,]
pie(table(Data_TR_V_gene[,6]))
table(str_length(Data_TR_V_gene[,4]))
Data_TR_V_gene[,4]
```

## Petite famille : non_stop_decay

```{r}
which(Data$transcriptBiotype == "non_stop_decay")
Data_non_stop_decay = which(Data$transcriptBiotype == "non_stop_decay")
Data_non_stop_decay = Data[Data_non_stop_decay,]
pie(table(Data_non_stop_decay[,6]))
table(str_length(Data_non_stop_decay[,4]))
sort(unique(Data_non_stop_decay[,4]))
```





















