---
title: "Test student"
author: Anaïs Vannutelli
date: 22/02/2018
output: 
   html_document: 
      toc: TRUE
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library("plyr")
```

# Creation of list 

```{r}
Coding=c('IG_C_gene', 'IG_D_gene', 'IG_J_gene', 'IG_LV_gene', 'IG_M_gene', 'IG_V_gene', 'IG_Z_gene', 'nonsense_mediated_decay', 'nontranslating_CDS', 'non_stop_decay', 'protein_coding', 'TR_C_gene', 'TR_D_gene', 'TR_gene', 'TR_J_gene', 'TR_V_gene')

Pseudogene=c('transcribed_unitary_pseudogene','disrupted_domain', 'IG_C_pseudogene', 'IG_J_pseudogene', 'IG_pseudogene', 'IG_V_pseudogene', 'processed_pseudogene', 'pseudogene', 'transcribed_processed_pseudogene', 'transcribed_unprocessed_pseudogene', 'translated_processed_pseudogene', 'translated_unprocessed_pseudogene', 'TR_J_pseudogene', 'TR_V_pseudogene', 'unitary_pseudogene', 'unprocessed_pseudogene','polymorphic_pseudogene')

LongNC=c('macro_lncRNA','bidirectional_promoter_lncRNA','sense_intronic','3prime_overlapping_ncRNA','ambiguous_orf','antisense','lincRNA','ncrna_host','non_coding','processed_transcript','retained_intron','sense_overlapping')

ShortNC=c('3prime_overlapping_ncRNA','scaRNA','miRNA', 'miRNA_pseudogene', 'misc_RNA', 'misc_RNA_pseudogene', 'Mt_rRNA' ,'Mt_tRNA', 'Mt_tRNA_pseudogene', 'ncRNA', 'pre_miRNA', 'RNase_MRP_RNA', 'RNase_P_RNA', 'rRNA', 'rRNA_pseudogene', 'scRNA_pseudogene', 'snlRNA', 'snoRNA', 'snoRNA_pseudogene', 'snRNA', 'snRNA_pseudogene', 'SRP_RNA', 'tmRNA', 'tRNA', 'tRNA_pseudogene')

Predictif=c('TEC')

NonCoding=c('macro_lncRNA','bidirectional_promoter_lncRNA','sense_intronic','3prime_overlapping_ncRNA','ambiguous_orf','antisense','lincRNA','ncrna_host','non_coding','processed_transcript','retained_intron','sense_overlapping','3prime_overlapping_ncRNA','scaRNA','miRNA', 'miRNA_pseudogene', 'misc_RNA', 'misc_RNA_pseudogene', 'Mt_rRNA' ,'Mt_tRNA', 'Mt_tRNA_pseudogene', 'ncRNA', 'pre_miRNA', 'RNase_MRP_RNA', 'RNase_P_RNA', 'rRNA', 'rRNA_pseudogene', 'scRNA_pseudogene', 'snlRNA', 'snoRNA', 'snoRNA_pseudogene', 'snRNA', 'snRNA_pseudogene', 'SRP_RNA', 'tmRNA', 'tRNA', 'tRNA_pseudogene')
SupraFamilyName=c('Coding', 'NonCoding', 'Pseudogene', 'Predictif')

NameFileMouse = c("3prime_overlapping_ncRNA","polymorphic_pseudogene","transcribed_processed_pseudogene","bidirectional_promoter_lncRNA","processed_pseudogene","transcribed_unitary_pseudogene","IG_C_gene","processed_transcript","transcribed_unprocessed_pseudogene","IG_V_gene","protein_coding","translated_processed_pseudogene","IG_V_pseudogene","pseudogene","TR_C_gene","lincRNA","retained_intron","TR_V_gene","macro_lncRNA","rRNA","TR_V_pseudogene","miRNA","sense_intronic","unitary_pseudogene","misc_RNA","sense_overlapping","unprocessed_pseudogene","nonsense_mediated_decay","snoRNA","non_stop_decay","TEC")

NameFileHuman = c("3prime_overlapping_ncRNA","antisense","bidirectional_promoter_lncRNA","IG_C_gene","IG_C_pseudogene","IG_V_gene","IG_V_pseudogene","lincRNA","macro_lncRNA","miRNA","misc_RNA","non_coding","nonsense_mediated_decay","non_stop_decay","polymorphic_pseudogene","processed_pseudogene","processed_transcript","protein_coding","pseudogene","retained_intron","rRNA","sense_intronic","sense_overlapping","TEC","transcribed_processed_pseudogene","transcribed_unitary_pseudogene","transcribed_unprocessed_pseudogene","TR_C_gene","TR_V_gene","TR_V_pseudogene","unitary_pseudogene","unprocessed_pseudogene")

AllSubFamilly = unique(c(Coding, Pseudogene, LongNC, ShortNC, Predictif))
```

# Fonction

## Data import

```{r}
DataImport = function(path, NameFileM, NameFileH) {
  Data_Frequency = list() # initialisation of the list
  Data_Frequency[[1]] = data.frame()
  Data_Frequency[[2]] = data.frame()
#  for(i in seq(1, length(NameFileM))){
#    filename = paste(path, "Mouse/All/Subset/Frequency/Frequency_", NameFileM[i],".csv", sep="")# creation of the input filename
#    tmp = read.csv(filename, header = F, sep = "\t") # read the input file in a tmp
#    tmp[is.na(tmp)] <- 0
#    tmp$subfamily = NameFileM[i] # adding of the subfamily
#    Data_Frequency[[1]] = rbind.fill(tmp, Data_Frequency[[1]]) # new subfamily add next to the other
#  }
  for(i in seq(1, length(NameFileH))){
    filename = paste(path, "Human/All/Subset/Frequency/Frequency_", NameFileH[i],".csv", sep="")# creation of the input filename
    print(filename)
    tmp = read.csv(filename, header = F, sep = "\t") # read the input file in a tmp
    tmp[is.na(tmp)] <- 0
    tmp$subfamily = NameFileH[i] # adding of the subfamily
    Data_Frequency[[2]] = rbind.fill(tmp, Data_Frequency[[2]]) # new subfamily add next to the other
  }
  return(Data_Frequency)
}
```

# Main

## Import of Data
```{r}
#pathMousePrac='/home/anais/Documents/Data/Mouse/All/Subset/'
#pathHumanPrac='/home/anais/Documents/Data/Human/All/Subset/'
#pathMouseCoBius = '/home/local/USHERBROOKE/vana2406/Documents/Data/mouse/All/Subset/'
#pathHumanCoBius = '/home/local/USHERBROOKE/vana2406/Documents/Data/human/Subset/'
#pathMacMouse = '/Users/patate/Documents/Data/mouse/All/Subset/'
#pathMacHuman = '/Users/patate/Documents/Data/human/All/Subset/'

#tmp = read.csv('/home/anais/Documents/Data/Human/All/Subset/Frequency_3prime_overlapping_ncRNA.csv', header = F, sep = "\t")
#tmp[is.na(tmp)] <- 0

Data_Frequency = list()
Data_Frequency = DataImport('/home/local/USHERBROOKE/vana2406/Documents/Data/', NameFileMouse, NameFileHuman)
```

```{r}


shapiro.test(mouse)
shapiro.test(human)

mean(mouse)
mean(human)

var.test(mouse,human)

t.test(human,mouse,var.equal = T)

wilcox.test(human,mouse)
```

