---
title: "Test student"
author: Anaïs Vannutelli
date: 22/02/2018
output: 
   html_document: 
      toc: TRUE
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library("plyr")
```

# Creation of list 

```{r}
Coding=c('IG_C_gene', 'IG_D_gene', 'IG_J_gene', 'IG_LV_gene', 'IG_M_gene', 'IG_V_gene', 'IG_Z_gene', 'nonsense_mediated_decay', 'nontranslating_CDS', 'non_stop_decay', 'protein_coding', 'TR_C_gene', 'TR_D_gene', 'TR_gene', 'TR_J_gene', 'TR_V_gene')

Pseudogene=c('transcribed_unitary_pseudogene','disrupted_domain', 'IG_C_pseudogene', 'IG_J_pseudogene', 'IG_pseudogene', 'IG_V_pseudogene', 'processed_pseudogene', 'pseudogene', 'transcribed_processed_pseudogene', 'transcribed_unprocessed_pseudogene', 'translated_processed_pseudogene', 'translated_unprocessed_pseudogene', 'TR_J_pseudogene', 'TR_V_pseudogene', 'unitary_pseudogene', 'unprocessed_pseudogene','polymorphic_pseudogene')

LongNC=c('macro_lncRNA','bidirectional_promoter_lncRNA','sense_intronic','3prime_overlapping_ncRNA','ambiguous_orf','antisense','lincRNA','ncrna_host','non_coding','processed_transcript','retained_intron','sense_overlapping')

ShortNC=c('3prime_overlapping_ncRNA','scaRNA','miRNA', 'miRNA_pseudogene', 'misc_RNA', 'misc_RNA_pseudogene', 'Mt_rRNA' ,'Mt_tRNA', 'Mt_tRNA_pseudogene', 'ncRNA', 'pre_miRNA', 'RNase_MRP_RNA', 'RNase_P_RNA', 'rRNA', 'rRNA_pseudogene', 'scRNA_pseudogene', 'snlRNA', 'snoRNA', 'snoRNA_pseudogene', 'snRNA', 'snRNA_pseudogene', 'SRP_RNA', 'tmRNA', 'tRNA', 'tRNA_pseudogene')

Predictif=c('TEC')

NonCoding=c('macro_lncRNA','bidirectional_promoter_lncRNA','sense_intronic','3prime_overlapping_ncRNA','ambiguous_orf','antisense','lincRNA','ncrna_host','non_coding','processed_transcript','retained_intron','sense_overlapping','3prime_overlapping_ncRNA','scaRNA','miRNA', 'miRNA_pseudogene', 'misc_RNA', 'misc_RNA_pseudogene', 'Mt_rRNA' ,'Mt_tRNA', 'Mt_tRNA_pseudogene', 'ncRNA', 'pre_miRNA', 'RNase_MRP_RNA', 'RNase_P_RNA', 'rRNA', 'rRNA_pseudogene', 'scRNA_pseudogene', 'snlRNA', 'snoRNA', 'snoRNA_pseudogene', 'snRNA', 'snRNA_pseudogene', 'SRP_RNA', 'tmRNA', 'tRNA', 'tRNA_pseudogene')
SupraFamilyName=c('Coding', 'NonCoding', 'Pseudogene', 'Predictif')

NameFileMouse = c("3prime_overlapping_ncRNA","polymorphic_pseudogene","transcribed_processed_pseudogene","bidirectional_promoter_lncRNA","processed_pseudogene","transcribed_unitary_pseudogene","IG_C_gene","processed_transcript","transcribed_unprocessed_pseudogene","IG_V_gene","protein_coding","translated_processed_pseudogene","IG_V_pseudogene","pseudogene","TR_C_gene","lincRNA","retained_intron","TR_V_gene","macro_lncRNA","rRNA","TR_V_pseudogene","miRNA","sense_intronic","unitary_pseudogene","misc_RNA","sense_overlapping","unprocessed_pseudogene","nonsense_mediated_decay","snoRNA","non_stop_decay","TEC")

NameFileHuman = c("3prime_overlapping_ncRNA","antisense","bidirectional_promoter_lncRNA","IG_C_gene","IG_C_pseudogene","IG_V_gene","IG_V_pseudogene","lincRNA","macro_lncRNA","miRNA","misc_RNA","non_coding","nonsense_mediated_decay","non_stop_decay","polymorphic_pseudogene","processed_pseudogene","processed_transcript","protein_coding","pseudogene","retained_intron","rRNA","sense_intronic","sense_overlapping","TEC","transcribed_processed_pseudogene","transcribed_unitary_pseudogene","transcribed_unprocessed_pseudogene","TR_C_gene","TR_V_gene","TR_V_pseudogene","unitary_pseudogene","unprocessed_pseudogene")

AllSubFamilly = unique(c(Coding, Pseudogene, LongNC, ShortNC, Predictif))
```

# Fonction

## Data import

```{r}
DataImport = function(path, NameFileM, NameFileH) {
  Data_Frequency = list() # initialisation of the list
  Data_Frequency[[1]] = data.frame()
  Data_Frequency[[2]] = data.frame()
  for(i in seq(1, length(NameFileM))){
    filename = paste(path, "Mouse/All/Subset/Frequency_", NameFileM[i],".csv", sep="")# creation of the input filename
    tmp = read.csv(filename, header = F, sep = "\t") # read the input file in a tmp
    tmp[is.na(tmp)] <- 0
    tmp$subfamily = NameFileM[i] # adding of the subfamily
    Data_Frequency[[1]] = rbind.fill(tmp, Data_Frequency[[1]]) # new subfamily add next to the other
  }
  for(i in seq(1, length(NameFileH))){
    filename = paste(path, "Human/All/Subset/Frequency_", NameFileH[i],".csv", sep="")# creation of the input filename
    print(filename)
    tmp = read.csv(filename, header = F, sep = "\t") # read the input file in a tmp
    tmp[is.na(tmp)] <- 0
    tmp$subfamily = NameFileH[i] # adding of the subfamily
    Data_Frequency[[2]] = rbind.fill(tmp, Data_Frequency[[2]]) # new subfamily add next to the other
  }
  return(Data_Frequency)
}
```

# Main

## Import of Data
```{r}
pathMousePrac='/home/anais/Documents/Data/Mouse/All/Subset/'
pathHumanPrac='/home/anais/Documents/Data/Human/All/Subset/'
#pathMouseCoBius = '/home/local/USHERBROOKE/vana2406/Documents/Data/mouse/All/Subset/'
#pathHumanCoBius = '/home/local/USHERBROOKE/vana2406/Documents/Data/human/Subset/'
#pathMacMouse = '/Users/patate/Documents/Data/mouse/All/Subset/'
#pathMacHuman = '/Users/patate/Documents/Data/human/All/Subset/'

#tmp = read.csv('/home/anais/Documents/Data/Human/All/Subset/Frequency_3prime_overlapping_ncRNA.csv', header = F, sep = "\t")
#tmp[is.na(tmp)] <- 0

Data_Frequency = list()
Data_Frequency = DataImport('/home/anais/Documents/Data/', NameFileMouse, NameFileHuman)
```

```{r}
mouse = c(1.086563,0.589797,0.312663,0.272926,0.164813,0.961847,0.566893,0.540249,0.22779,0.362056,0.31506,0.783085,0.129381,0.173263,1.547389,0.292312,3.061224,0.089819,0.096918,0.096488,0.278674,0.09697,0.097518,0.097528,0.098107,0.098058,0.068484,0.074881,0.097238,0.097409,0.146456,2.623524,1.927525,0.263296,0.098198,1.304915,0.050075,0.949668,0.111268,0.997009,0.098188,3.311258,0.490316,1.148294,0.097509,1.56658,0.473485,2.027369,0.134066,0.04565,0.068951,1.118568,0.193667,0.298864,0.772798,0.09689,0.097409,1.29199,0.121862,0.068222,0.068297,0.050053,0.065776,0.068255,0.098058,0.098121,0.066551,0.096488,0.159719,0.259673,0.362319,0.098063,0.2772,0.800641,0.055066,0.490436,0.104297,0.135777,0.089509,0.097395,0.311139,0.049983,0.067995,0.124922,0.068287,0.078542,0.470146,0.072553,0.396668,0.067843,0.068395,0.207348,0.208681,0.494315,0.273299,0.595948,0.156,0.149091,0.310527,0.041478,0.150807,0.171566,0.166141,0.454804,0.085951,0.434075,0.176243,0.186393,0.358423,0.092799,0.050885,0.284199,0.116464,0.112524,0.091199,0.112385,0.484966,0.126064,0.055997,0.381437,0.150466,0.247036,0.198965,0.125116,0.079904,0.126171,0.287404,1.15942,0.433463,0.170106,0.090572,4.962779,0.070883,1.345895,0.13563,0.313742,2.857143,0.210504,0.185094,0.146402,0.077122,2.022245,0.594884,0.227609,0.467727,0.248262,0.164718,0.074632,0.113327,0.079202,0.05214,1.35318,0.115095,0.129467,1.258149,0.777152,0.334695,0.423908,0.249911,0.525486,1.42898,0.228683,0.228691,0.249866,0.554324,0.201708,0.403714,0.337724,0.101729,0.514933,0.518672,0.581734,0.40016,0.40783,0.560538,0.145539,0.58072,0.161558,0.565185,2.840909,0.21148,1.520913,0.562701,0.193784,0.24644,0.250438,0.527148,0.773395,0.414938,0.46853,0.933707,0.315457,1.997337,2.793296,0.279564,0.197511,0.429553,0.954502,0.176845,0.367512,0.426621,0.426439,0.094056,0.427716,0.178955,0.429185,0.428633,0.074134,0.32911,0.060689,0.340832,0.120384,0.977517,0.201857,1.539646,0.466056,0.220946,0.405022,0.110144,0.147341,0.076899,0.073035,0.486618,5.347594,0.061142,0.667111,0.04397,0.531632,0.953289,3.215434,0.883392,0.454545,5.36193,4.86618,3.037206,0.765697,2.762431,1.443001,0.217794,5.347594,5.698006,5.36193,0.092242,0.455166,0.212422,0.123411,0.116288,0.060787,0.071372,0.118737,0.881057,0.163052,0.242248,0.065915,0.16292,1.144165,0.108225,0.054642,0.062716,0.053599,0.175125,0.210003,3.115265,0.138472,1.059883,0.102619,3.436426,3.134796,0.91659,0.083309,0.320051,0.260138,0.381679,0.493705,0.214996,0.264201,0.076511,0.180825,0.539738,0.255167,0.512033,0.164501,0.588582,0.225938,5.037783,0.514271,0.253614,0.422476,0.452899,0.492975,0.169029,1.24533,0.727802,0.381534,0.081593,0.162033,2.381267,0.083689,0.1386,0.329164,0.069262,0.070343,0.169823,1.16144,0.070274,0.21245,0.069339,0.198562,0.063694,0.116374,0.16384,0.298107,0.985222,0.246475,0.201809,0.104174,3.125,0.279542,0.029395,0.564653,0.083696,3.571429,0.16415,0.229148,0.411862,0.084836,3.745318,0.12643,0.072176,0.194489,0.334057,0.18867,0.181143,0.128623,0.1401,0.340175,0.164935,0.10642,0.148544,0.367512,0.124533,0.085657,0.364697,0.183453,0.066432,0.031143,0.119861,0.67659,0.262192,2.232143,0.086147,0.050221,0.109278,0.163092,0.817661,0.819001,1.5625,0.049021,0.090932,0.17336,0.745459,0.582185,2.793296,0.74239,2.061856,0.225683,0.247852,0.093019,0.140746,0.381679,0.533049,0.101916,0.448632,0.380156,0.117174,0.380518,0.059605,0.297974,0.13488,0.231201,0.303122,0.216263,0.11552,0.381752,0.554529,0.090363,1.0,0.114574,0.832639,0.165673,0.122444,0.81367,0.948767,1.142857,0.16675,0.163693,0.277855,0.29967,0.149312,0.381679,0.086896,0.814332,0.173928,0.149254,0.094944,0.411353,0.073779,0.090992,0.179147,0.458716,0.285959,0.808407,0.638162)
human = c(0.660834,0.180652,0.850112,2.318393,1.130103,0.036885,0.460448,1.237624,1.010739,1.317523,0.197697,0.085551,0.05148,0.10866,0.098561,0.221582,0.070467,0.131541,0.518403,0.050841,0.339616,0.10099,0.70373,0.187512,0.064123,0.0524,0.051501,0.151561,0.243754,1.942825,0.288711,1.345895,0.666519,0.139602,0.155521,0.14573,0.635324,0.268649,3.311258,0.083744,0.95511,0.648088,0.099341,0.238906,0.088739,0.155263,0.557207,0.286656,0.152045,0.13245,0.273038,0.715564,0.62135,0.523423,1.148912,0.274215,0.284576,0.04038,0.532481,0.33855,0.112579,1.145475,3.891051,1.169591,0.081162,0.259538,0.203957,0.709723,0.554939,0.201167,0.449352,0.310174,0.110983,0.496208,0.326052,0.407048,0.051813,0.077714,0.108147,0.117779,1.976285,0.104346,0.104259,1.398601,0.537634,0.064914,0.577256,0.401699,1.461988,0.495786,1.919386,0.939629,2.843602,1.197127,0.593824,0.280414,1.360544,1.087745,1.081081,1.360544,1.074499,0.935454,0.130651,0.11217,1.973684,0.380011,0.149914,1.103347,1.27011,0.874585,0.075543,0.274725,0.076959,0.273673,0.505051,8.695652,0.275028,0.274876,1.088139,1.35318,1.02145,0.273673,0.359454,0.307882,1.344086,1.157742,1.057952,1.639344,0.958379,2.579536,1.870324,1.418749,1.265022,1.157407,0.385635,2.502085,0.29894,1.861504,0.173433,0.463607,0.440386,0.321699,1.059883,0.095012,0.164123,0.108545,0.025481,0.118701,2.132196,0.055221,0.725163,0.350324,0.044311,0.118948,0.303076,0.021428,0.049556,3.546099,1.580611,0.126446,1.094092,0.117897,0.410846,0.34976,1.341982,1.098147,1.079214,1.251564,0.961908,0.175932,0.839772,0.070919,2.876663,0.252207,0.55731,0.948767,3.181336,0.083546,0.40347,0.620964,1.407129,4.411765,2.879079,1.175318,0.07178,3.051882,3.181336,0.403388,0.087017,0.059395,0.022124,0.573559,1.226994,0.166583,1.838235,0.022134,0.318573,1.470048,0.392465,0.261849,1.282051,0.635786,1.089799,2.050581,0.898357,1.235076,0.169722,3.968254,0.215641,0.129066,0.553128,0.379651,0.911162,1.026167,2.280502,1.074114,1.930502,6.802721,0.402901,10.695187,1.011634,0.131735,4.158004,0.20829,2.840909,2.074689,1.097695,0.496278,0.631712,0.207727,0.040293,0.464792,0.468242,0.530874,0.208438,5.649718,1.014052,0.114005,2.792182,0.330579,1.78731,0.478985,0.115001,0.292113,1.005025,1.689189,0.175809,0.086733,0.113827,1.071237,0.240645,0.410813,2.23914,0.465333,0.95039,0.026992,0.192064,0.652955,2.574003,0.121124,0.227946,0.21527,1.680672,0.145349,0.766284,0.174216,3.667482,0.705716,0.154787,1.271186,0.044049,0.34379,0.023252,0.289939,6.024096,0.262927,0.075199,1.210654,0.175809,1.201923,0.035141,1.253133,1.16144,1.201923,1.492537,0.104613,0.051059,0.218994,0.486027,0.071946,0.670017,0.393082,0.818666,0.335796,1.234568,0.928505,1.050788,0.986193,0.595238,1.055223,0.151745,1.092498,0.34002,0.25641,0.18423,0.297089,1.680672,1.585205,0.330579,1.922384,1.616379,0.862069,0.138889,1.658375,2.671416,1.228702,1.323335,0.776598,0.172344,0.042893,0.33761,1.186944,2.319289,0.278164,0.356888,1.043297,2.158273,0.210482,0.076034,2.293578,0.190078,0.31837,0.464422,0.3885,0.217533,0.601323,1.386322,1.22399,0.58651,0.798722,0.103146,1.926782,0.450045,0.498008,0.130685,0.470514,0.07931,0.20007,0.369315,0.671216,0.083249,1.228879,0.475511,0.135483,0.154392,1.094391,0.581734,2.047083,1.025641,0.649984,0.277316,0.033238,0.555247,0.022994,0.50226,1.103753,0.064881,0.965562,1.111464,0.139938,0.138255,0.118371,0.161361,1.096792,0.358359,0.795292,0.350018,0.066094,0.627353,0.086851,0.139821,0.960615,0.768049,0.289146,0.202061,0.249507,0.156018,0.129826,0.920175,0.188005,0.545852,0.078449,0.15601,0.03309,0.100969,0.678887,0.686342,0.575043,3.095975,0.202102,0.552384,0.087317,0.273299,0.202799,0.763942,0.180571,0.068589,1.018849,0.31511,0.628931,0.20803,0.310174,4.422333,0.159274,0.316706,0.099651,0.433276,0.846024,4.672897,0.137956,1.845018,2.012072,1.177856,1.72117,0.131105,2.207506,0.29994,0.70028,0.137703,0.095386,0.290951,0.049091,0.180434,1.837485,1.518219,1.270648,0.343383,0.97561,0.109763,0.688705,0.799488,0.962001,0.18162,0.200421,0.177873,0.141603,0.930632,0.139968,0.462892,0.176129,1.18859,0.985028,0.116877,0.673219,0.410706,0.946074,0.437473,0.457429,2.193857,0.202511,0.981547,0.257417,1.012761,0.466926,0.514403,0.14988,0.196831,0.101163,0.853971,1.36612,0.966931,0.053319,0.334616,0.019678,0.08035,0.288517,0.027188,1.030928,1.207729,0.219202,0.693001,0.849377,1.239926,1.197605,1.120448,0.129862,0.979792,0.268697,1.239926,1.239926,0.048127,1.239926,1.239926,1.239926,1.239926,0.048695,0.664894,1.240695,1.23839,1.239157,0.805802,1.239926,1.239157,1.848429,1.239926,1.239926,1.239926,0.619963,1.239926,0.417711,0.223339,0.800587,0.259441,1.945525,0.060863,1.344086,0.934704,0.062842,0.934579,0.934954,0.933645,1.573812,0.549904,0.029037,0.157644,0.934579,0.112778,1.077586,0.03448,0.186335,0.900901,0.061631,1.10595,1.378043,1.945525,0.118939,0.218747,4.424779,0.231965,0.21796,0.145921,0.679348,0.495786,0.084696,0.058302,1.009082,1.039501,1.66251,0.410172,1.517451,0.303841,5.926724,0.126823,4.504505,0.067897,0.307882,1.106195,0.917852,0.210659,0.073046,0.220095,0.079227,1.874414,0.161022,0.791766,1.697793,0.12663,0.218723,0.219829,0.113714,0.246853,0.123487,2.115656,0.084178,0.281153,2.75672,1.255493,0.39984,0.063281,1.118568,0.299083,0.203142,0.683527,0.038862,0.063299,0.139237,0.2457,2.80112,1.239926,1.644737,0.607533,0.383215,2.597403,0.095034,2.096436,0.085893,0.68306,1.644737,1.892915,0.11812,1.29199,0.094854,0.070264,0.063865,0.507357,0.038824,0.691563,0.044483,0.230097,0.116185,0.152253,2.280502,0.106933,0.0534,0.165631,0.794913,2.071823,1.40746,2.084781,1.40746,2.09937,0.063303,0.062473,2.781641,0.191058,0.056183,0.068376,0.057376,1.142857,0.045035,0.090188,0.066827,0.099423,0.59988,0.056016,0.068432,0.209336,0.079548,1.109878,0.139978,0.665336,0.0702,0.066845,0.752445,0.097135,0.514668,3.0326,0.06839,0.281057)

shapiro.test(mouse)
shapiro.test(human)

var.test(mouse,human)

wilcox.test(human,mouse)
```

