---
title: "NbG4"
author: "Anaïs Vannutelli"
date: "April 24, 2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Densité de G4 par CG content

```{r}
nbG4 <- read.delim("~/Documents/Data/Genomes/All_sp/nbG4.tsv", stringsAsFactors = FALSE)
label = nbG4[1,]
nbG4 = nbG4[2:62,]
tablePlot = data.frame(as.numeric(as.character(nbG4$Density)), as.numeric(as.character(nbG4$GC.content)), nbG4$X.1, nbG4[,1])
rownames(tablePlot) = nbG4[,1]
library(ggplot2)
#install.packages('ggplot2')
ggplot(tablePlot, aes(x=tablePlot$as.numeric.as.character.nbG4.GC.content.., y=tablePlot$as.numeric.as.character.nbG4.Density.., color=tablePlot$nbG4.X.1)) + 
    geom_point(size=5, alpha=0.6) + 
    labs(title = 'Densité de pG4 (pG4/kb) en fonction du contenu en GC (%) ', x = 'Contenu en GC', y = 'Densité de pG4 (pG4/kb)', colour = 'Clade', caption = "Données des gènes") + ylim(0, 0.35)

ggplot(tablePlot, aes(x=tablePlot$as.numeric.as.character.nbG4.Density.., y=tablePlot$as.numeric.as.character.nbG4.GC.content.., color=tablePlot$nbG4.X.1, label = tablePlot$nbG4...1.)) + 
    geom_point() + geom_text(aes(label = tablePlot$nbG4...1.)) +
    labs(title = 'Density of pG4 (pG4/kb) and GC content', x = 'Density of pG4 (pG4/kb)', y = '% of GC in genes', colour = 'Clade', caption = "based on data from genes") + xlim(0, 0.35)
```

# BoxPlot score

```{r}
# library
library(ggplot2)
 
# The mtcars dataset is proposed in R
head(mpg)
 
# plot
ggplot(diamonds, aes(x=carat, y=price)) +
  geom_boxplot(fill="skyblue", aes(group = cut_width(carat, 0.5)))
```


# line plot
```{r}
library(gridExtra)
library(ggplot2)
library(grid)
Density_random <- read_delim("Documents/Data/Genomes/All_sp/Density_random.tsv", "\t", escape_double = FALSE, trim_ws = TRUE)

colnames(Density_random) <- c("Specie", "Value", "Type", "sd")
density = Density_random[1:124,]
GC = Density_random[125:186,]
GC = GC[,1:3]
attach(density)

Density_random$Specie=factor(Density_random$Specie, levels=unique(Density_random$Specie))
density$Specie=factor(density$Specie, levels=unique(density$Specie))
GC$Specie=factor(GC$Specie, levels=unique(GC$Specie))

p1 <- ggplot(density, aes(x=Specie, y=Value, group=Type)) +
      geom_errorbar(aes(ymin=Value-sd, ymax=Value+sd,color=Type), width=.1) +
      geom_line(aes(color=Type)) +
      geom_point(aes(color=Type)) +
      ggtitle("Density\n")+
      theme(axis.text.x = element_text(angle = 90, hjust = 1))+
      xlab("")
p1

## Create the top plot (with negative bottom margins)
g.top <- ggplot(GC, aes(x=Specie, y=Value, group=Type, color="#E69F00")) +
  theme_bw() +
  theme(plot.margin = unit(c(1,5,-30,6),units="points"),
        axis.title.y = element_text(vjust =0.25)) +
  theme(legend.position="bottom")+
  geom_point(color="#E69F00") +
  geom_line(color="#E69F00") +
  #scale_color_manual(values="#E69F00")+
  labs(y = "GC content", main="pG4 density for each species, and the GC content of each specie.")

## Create the bottome plot (with no top margins)
g.bottom <- ggplot(density, aes(x=Specie, y=Value, group=Type)) +
  theme_bw() +
  theme(plot.margin = unit(c(0,5,1,1),units="points")) +
  theme(legend.position="bottom")+
  geom_errorbar(aes(ymin=Value-sd, ymax=Value+sd,color=Type), width=.1) +
  geom_point(aes(color=Type)) +
  geom_line(aes(color=Type)) +
  labs(y = "Density of pG4 (pG4/kb)")+
  theme(axis.text.x = element_text(angle = 90, hjust = 1))

## Plot graphs and set relative heights
grid.arrange(g.top,g.bottom, heights = c(1/5, 4/5)) 
```

