DROP TABLE G4;
DROP TABLE Transcrits;
DROP TABLE G4_and_Transcripts;
DROP TABLE Genes_and_Transcripts;

CREATE TABLE G4
(idG4 VARCHAR(20) CONSTRAINT pk_idG4 PRIMARY KEY,
Specie CHAR(2),
Chromosome VARCHAR(2),
Strand VARCHAR(2),
Coord1 NUMBER(10),
Coord2 NUMBER(10),
cGcC FLOAT,
G4H FLOAT,
G4Screener FLOAT,
rG4 LONGTEXT(2470));

CREATE TABLE Transcripts
(Specie CHAR(2) CONSTRAINT fk_sp REFERENCES G4(Specie),
idTranscript VARCHAR(30) CONSTRAINT pk_idtr PRIMARY KEY,
Chromosome VARCHAR(2) CONSTRAINT fk_chr REFERENCES G4(Chromosome),
Strand VARCHAR(2) CONSTRAINT fk_Strd REFERENCES G4(Strand),
idGene VARCHAR(30),
Biotype VARCHAR(30));

CREATE TABLE G4_and_Transcripts
(idLink VARCHAR(20) CONSTRAINT pk_idLink PRIMARY KEY,
Specie CHAR(2) CONSTRAINT fk_sp REFERENCES G4(Specie),
idG4 VARCHAR(20) CONSTRAINT fk_idG4 REFERENCES G4(idG4),
idTranscript VARCHAR(30) CONSTRAINT fk_idTr REFERENCES Transcripts(idTranscript),
Localisation VARCHAR(30));
