#!/usr/bin/env python
# -*- coding: utf-8 -*-:v

def dicoSp():
    {'Homo sapiens' : 'Eukaryota',
    'Pan troglodytes' : 'Eukaryota',
    'Pongo abelii' : 'Eukaryota',
    'Mus musculus' : 'Eukaryota',
    'Monodelphis domestica' : 'Eukaryota',
    'Anolis carolinensis' : 'Eukaryota',
    'Ornithorhynchus anatinus' : 'Eukaryota',
    'Gallus gallus' : 'Eukaryota',
    'Danio rerio' : 'Eukaryota',
    'Gasterosteus aculeatus' : 'Eukaryota',
    'Caenorhabditis elegans' : 'Eukaryota',
    'Drosophila melanogaster' : 'Eukaryota',
    'Apis mellifera' : 'Eukaryota',
    'Oryza sativa' : 'Eukaryota',
    'Chlamydomonas reinhardtii' : 'Eukaryota',
    'Physcomitrella patens' : 'Eukaryota',
    'Solanum lycopersicum' : 'Eukaryota',
    'Vitis vinifera' : 'Eukaryota',
    'Arabidopsis thaliana' : 'Eukaryota',
    'Aspergillus nidulans' : 'Eukaryota',
    'Neurospora crassa' : 'Eukaryota',
    'Saccharomyces cerevisiae' : 'Eukaryota',
    'Schizosaccharomyces pombe' : 'Eukaryota',
    'Dictyostelium discoideum' : 'Eukaryota',
    'Leishmania major' : 'Eukaryota',
    'Campylobacter jejuni subsp. jejuni NCTC 11168 = ATCC 700819 strain NCTC 11168' : 'Bacteria',
    'Brucella abortus bv. 1 str. 9-941' : 'Bacteria',
    'Yersinia pestis biovar microtus str 91001' : 'Bacteria',
    'Anaplasma phagocytophilum str. HZ' : 'Bacteria',
    'Chloroflexus aurantiacus J-10-fl' : 'Bacteria',
    'Haemophilus influenzae Rd KW20' : 'Bacteria',
    'Legionella pneumophila str. Paris' : 'Bacteria',
    'Vibrio cholerae O1 biovar El Tor str. N16961' : 'Bacteria',
    'Staphylococcus aureus subsp. aureus N315' : 'Bacteria',
    'Francisella tularensis subsp. tularensis SCHU S4' : 'Bacteria',
    'Escherichia coli str. K-12 substr. MG1655' : 'Bacteria',
    'Bacillus subtilis subsp. subtilis str. 168' : 'Bacteria',
    'Mycobacterium tuberculosis H37Rv' : 'Bacteria',
    'Enterococcus faecalis V583' : 'Bacteria',
    'Mycoplasma pneumoniae M129' : 'Bacteria',
    'Streptococcus pneumoniae TIGR4' : 'Bacteria',
    'Borreliella burgdorferi B31' : 'Bacteria',
    'Thermus thermophilus HB8' : 'Bacteria',
    'Geobacter sulfurreducens PCA' : 'Bacteria',
    'Wolbachia endosymbiont of drosophila melanogaster' : 'Bacteria',
    'Aquifex aeolicus VF5' : 'Bacteria',
    'Myxococcus xanthus DK 1622' : 'Bacteria',
    'Neisseria meningitidis Z2491' : 'Bacteria',
    'Chlamydia trachomatis D/UW-3/CX' : 'Bacteria',
    'Nanoarchaeum equitans Kin4-M' : 'Archaea',
    'Pyrobaculum aerophilum str. IM2' : 'Archaea',
    'Methanobrevibacter smithii ATCC 35061' : 'Archaea',
    'Cenarchaeum symbiosum A' : 'Archaea',
    'Saccharolobus solfataricus P2' : 'Archaea',
    'Thermoplasma acidophilum DSM 1728' : 'Archaea',
    'Methanosarcina acetivorans C2A' : 'Archaea',
    'Pyrococcus horikoshii OT3' : 'Archaea',
    'Archaeoglobus fulgidus dsm 4304' : 'Archaea',
    'Candidatus Korarchaeum cryptofilum OPF8' : 'Archaea',
    'Halobacterium salinarum R1' : 'Archaea',
    'Hyperthermus butylicus DSM 5456' : 'Archaea'}
